#!/bin/bash
# Installation script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
# Check if bash-completion installed
if ! { dpkg-query -W -f='${Status}' bash-completion | grep "ok installed"; } > /dev/null 2>&1; then
  {
    echo "Bash Completion is not installed"
    echo "You must install it first in order to use this script"
    echo "Run: sudo apt-get install bash-completion"
  } 1>&2
  exit 1
elif ! [[ $(ps -acx | grep nginx | wc -l) > 0 ]] || { ! { dpkg-query -W -f='${Status}' nginx | grep "ok installed"; } > /dev/null 2>&1; }; then
  echo "Nginx is not installed/running" 1>&2
  exit 1
fi
# Check if -o nosort supported (Require bash 4.4+)
if printf '%s\n%s\n' "$BASH_VERSION" "4.4" | sort -rVC; then
  sortsupported="-o nosort"
else
  unset sortsupported
fi
ngxcondition="/root/.ngx_donotremove"
completionfile="/etc/bash_completion.d/nginxsite_complete"
if [ ! -f $ngxcondition ] || [ ! -f $completionfile ]; then
  if [ ! -d "/etc/bash_completion.d" ]; then mkdir -p "/etc/bash_completion.d"; fi
  nginx_available="/etc/nginx/sites-available"
  nginx_enabled="/etc/nginx/sites-enabled"
  scriptdir=$(dirname "$(readlink -f "$0")")
  # First run
  printf "Installing nginx site wrapper script..."
  # Installing autocomplete
  touch $ngxcondition
  cat << EOF >> "$completionfile"
# BEGIN AUTOCOMPLETE
function _site_complete()
{
  local cur opts sitepath
  case "\${COMP_LINE}" in
    *ensite*|*create*) sitepath="available";;
    *dissite*) sitepath="enabled";;
  esac
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  opts="--help --restart -h -r"
  [[ \$(ls -q /etc/nginx/sites-\${sitepath}/ | wc -l) -eq 1 ]] && COMPREPLY+=( $'\xC2\xA0' )

  if [[ "\${cur}" == -* ]]; then
    COMPREPLY=( \$(compgen -W "\${opts}" -- "\${cur}") )
    return 0
  else
    for filename in /etc/nginx/sites-\${sitepath}/"\${cur}"*; do
      [[ -f "\$filename" ]] || continue
      COMPREPLY+=( \$(echo "\${filename##*/}") )
    done
  fi
}

complete $sortsupported -F _site_complete ngxensite ngxdissite ngxcreate
# END AUTOCOMPLETE
EOF
# Creating directory if not exist
if [ ! -d "$nginx_available" ]; then mkdir -p "$nginx_available"; fi
if [ ! -d "$nginx_enabled" ]; then mkdir -p "$nginx_enabled"; fi
# Configure nginx to use sites-enabled
sed -i.ngx_backup '/include.*conf/ a\    include /etc/nginx/sites-enabled/*;' /etc/nginx/nginx.conf
mv /etc/nginx/nginx.conf.ngx_backup /etc/nginx/.nginx.conf.ngx_backup
# Moving executable
cp --no-preserve=mode,ownership "${scriptdir}/bin/ngxensite" /usr/local/bin/
cp --no-preserve=mode,ownership "${scriptdir}/bin/ngxdissite" /usr/local/bin/
cp --no-preserve=mode,ownership "${scriptdir}/bin/ngxcreate" /usr/local/bin/
chmod 755 /usr/local/bin/ngxensite /usr/local/bin/ngxdissite /usr/local/bin/ngxcreate
printf ' Done !\n'
else
  echo "Nginxsite already installed"
  exit 1
fi
