#!/bin/bash
# Installation script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
else
 nginx_available="/etc/nginx/sites-available"
 nginx_enabled="/etc/nginx/sites-enabled"
 scriptdir=$(dirname "$(readlink -f "$0")")
 ngxcondition="/root/.ngx_donotremove"
 USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
 completionfile="/etc/bash_completion.d/nginxsite_complete"
 # First run
 printf "Installing nginx site wrapper script..."
 # Installing autocomplete
 if [ ! -f $ngxcondition ]; then
   touch $ngxcondition
   cat <<'EOF' >> "$completionfile"
# BEGIN AUTOCOMPLETE
function _site_complete()
{
    local cur opts sitepath
    case ${COMP_LINE} in
      *ensite*|*create*) sitepath="available";;
      *dissite*) sitepath="enabled";;
    esac

    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts="--help --restart -h -r"

    if [[ ${cur} == -* ]]; then
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    else
      for filename in "/etc/nginx/sites-${sitepath}/"*; do
          [[ -f $filename ]] || continue
          COMPREPLY+=( $(echo ${filename##*/}) )
      done
    fi
    [[ $(ls -q /etc/nginx/sites-${sitepath}/ | wc -l) -eq 1 ]] && COMPREPLY+=( $'\xC2\xA0' )
}

complete -F _site_complete ngxensite ngxdissite ngxcreate
# END AUTOCOMPLETE
EOF
# Captured from .bashrc
if [ -f /usr/share/bash-completion/bash_completion ]; then
  . /usr/share/bash-completion/bash_completion
elif [ -f /etc/bash_completion ]; then
  . /etc/bash_completion
fi
# EndCapture
 fi
 # Creating directory if not exist
 if [ ! -d "$nginx_available" ]; then mkdir -p "$nginx_available"; fi
 if [ ! -d "$nginx_enabled" ]; then mkdir -p "$nginx_enabled"; fi
 # Configure nginx to use sites-enabled
 sed -i.ngx_backup '/include.*conf/ a\    include /etc/nginx/sites-enabled/*;' /etc/nginx/nginx.conf
 mv /etc/nginx/nginx.conf.ngx_backup /etc/nginx/.nginx.conf.ngx_backup
 # Moving executable
 cp --no-preserve=mode,ownership "${scriptdir}/bin/ngxensite" /usr/local/bin/
 cp --no-preserve=mode,ownership "${scriptdir}/bin/ngxdissite" /usr/local/bin/
 cp --no-preserve=mode,ownership "${scriptdir}/bin/ngxcreate" /usr/local/bin/
 chmod 755 /usr/local/bin/ngxensite /usr/local/bin/ngxdissite /usr/local/bin/ngxcreate
 printf ' Done !\n'
fi
