#!/bin/bash
# Uninstall script
ngxcondition="/root/.ngx_donotremove"
completionfile="/etc/bash_completion.d/nginxsite_complete"
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
elif [ -f $ngxcondition ] || [ -f $completionfile ]; then
  echo "Nginxsite already installed"
  exit 1
else
  scriptdir=$(dirname "$(readlink -f "$0")")
  printf "Removing nginx site wrapper script..."
  rm -f /usr/local/bin/ngxensite /usr/local/bin/ngxdissite /usr/local/bin/ngxcreate /root/.ngx_donotremove /etc/bash_completion.d/nginxsite_complete
  mv /etc/nginx/.nginx.conf.ngx_backup /etc/nginx/nginx.conf
  while [[ ! $wantremove =~ ^[yYnN]$ ]]; do
    read -s -n1 -p "Do you want to remove this (script) directory ? (y/n)" wantremove
    echo
    case "$wantremove" in
      [Yy]* ) rm -rf "$scriptdir"; echo "$scriptdir deleted" '!';;
      [Nn]* ) exit 0;;
      * ) echo "Invalid choice" >&2;;
    esac
  done
  printf ' Done !\n'
fi
